use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Clone)]
pub enum BootloaderType {
    Grub,
    SystemdBoot,
    Efi, // Fallback/Generic EFI
    Unknown,
}

/// The main artifact generated by kgen, describing the deployment
#[derive(Debug, Serialize, Deserialize)]
pub struct DeploymentConfig {
    pub network: NetworkConfig,
    pub auth: AuthConfig,
    // TargetNode removed as we focus on Alpine only
}

#[derive(Debug, Serialize, Deserialize, Default, Clone)]
pub struct NetworkConfig {
    pub interfaces: Vec<InterfaceConfig>,
    pub dns: Vec<String>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct InterfaceConfig {
    pub mac: String,
    pub name: String,           // Original name on host, for reference
    pub addresses: Vec<String>, // CIDR format
    pub gateway: Option<String>,
    pub gateway6: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Default, Clone)]
pub struct AuthConfig {
    pub root_password_hash: Option<String>, // if None, password login disabled
    pub ssh_authorized_keys: Vec<String>,
}
